num = int(input('Digite um numero:'))
num2 = int(input('Digite outro numero:'))
s = (num+num2)
# print('A soma entre',num,'e',num2,'é igual a:',s)
print('A soma entre {} e {} é igual a {}'.format(num,num2,s))
